const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const cell=v=>typeof v==='number'&&Number.isFinite(v)?`<c><v>${v}</v></c>`:`<c t="inlineStr"><is><t>${esc(v)}</t></is></c>`;
const sheet=rows=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,i)=>`<row r="${i+1}">${r.map(cell).join('')}</row>`).join('')}</sheetData></worksheet>`;
const enc=new TextEncoder(), table=(()=>{const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0;}return t;})();
const crc32=b=>{let c=0xffffffff;for(const x of b)c=table[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
const u16=n=>new Uint8Array([n&255,(n>>>8)&255]),u32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
const join=parts=>{const out=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let o=0;parts.forEach(p=>{out.set(p,o);o+=p.length;});return out;};
const zip=files=>{const ls=[],cs=[];let off=0;Object.entries(files).forEach(([name,text])=>{const n=enc.encode(name),d=enc.encode(text),crc=crc32(d);const l=join([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),n,d]);ls.push(l);cs.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(d.length),u32(d.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),n]));off+=l.length;});const body=join(ls),central=join(cs);return join([body,central,u32(0x06054b50),u16(0),u16(0),u16(cs.length),u16(cs.length),u32(central.length),u32(body.length),u16(0)]);};
const download=(blob,name)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const date=v=>!v?'':typeof v.toDate==='function'?v.toDate().toISOString():v.seconds?new Date(v.seconds*1000).toISOString():String(v);

export const exportPortfolioXlsx=(positions,snapshots)=>{
 const ph=['Institución','Producto','Categoría','Moneda','Saldo','Tasa anual %','Tipo tasa','Liquidez','Ganado informado','Último cambio','Inicio','Vencimiento','Info oficial','Fuente','Fuente verificada'];
 const pr=[ph,...positions.map(p=>[p.institution,p.name,p.category,p.currency,Number(p.balance||0),Number(p.annualRate||0),p.rateType,p.liquidity,Number(p.realizedEarnings||0),Number(p.lastEarning||0),p.startDate,p.maturityDate,p.infoUrl,p.sourceUrl,p.sourceCheckedAt])];
 const ms=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
 const fr=[['Institución','Fondo','Ticker',...ms.map(x=>x.toUpperCase()),'YTD publicado','NAV','Fecha NAV'],...positions.filter(p=>p.category==='FCI').map(p=>[p.institution,p.name,p.ticker,...ms.map(m=>Number(p.monthlyReturns?.[m]||0)),Number(p.publishedYtdReturn||0),Number(p.nav||0),p.navDate])];
 const hr=[['Institución','Producto','Moneda','Saldo','Tasa anual %','Fuente registro','Fecha'],...snapshots.map(s=>[s.institution,s.name,s.currency,Number(s.balance||0),Number(s.annualRate||0),s.source,date(s.capturedAt)])];
 const files={'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet3.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Posiciones" sheetId="1" r:id="rId1"/><sheet name="FCI mensual" sheetId="2" r:id="rId2"/><sheet name="Historial" sheetId="3" r:id="rId3"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet3.xml"/></Relationships>','xl/worksheets/sheet1.xml':sheet(pr),'xl/worksheets/sheet2.xml':sheet(fr),'xl/worksheets/sheet3.xml':sheet(hr)};
 download(new Blob([zip(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`portfolio-${new Date().toISOString().slice(0,10)}.xlsx`);
};

export const buildPortfolioLlmMarkdown=(positions,snapshots)=>{
 const totals=positions.reduce((a,p)=>{a[p.currency]=(a[p.currency]||0)+Number(p.balance||0);return a;},{});
 const l=['# Portfolio LTC — contexto para análisis LLM','',`Generado: ${new Date().toISOString()}`,'','## Reglas para el análisis','- No inventes datos faltantes ni tasas actuales.','- No mezcles monedas sin un tipo de cambio explícito.','- Diferencia cambios de saldo de ganancias de inversión.','- Señala concentración, liquidez, vencimientos, tasas posiblemente desactualizadas y fuentes sin verificar.','- Trata simulaciones como escenarios, no como rendimiento garantizado.','- Propón verificaciones concretas antes de recomendar movimientos.','','## Totales por moneda',...Object.entries(totals).map(([k,v])=>`- ${k}: ${v}`),'','## Posiciones'];
 positions.forEach(p=>{l.push('',`### ${p.institution} — ${p.name}`,`- Categoría: ${p.category}`,`- Moneda: ${p.currency}`,`- Saldo: ${p.balance}`,`- Tasa cargada: ${p.annualRate||'N/D'}% ${p.rateType||''}`,`- Liquidez: ${p.liquidity||'N/D'}`,`- Ganado informado: ${p.realizedEarnings??'N/D'}`,`- Fuente oficial: ${p.sourceUrl||p.infoUrl||'N/D'}`,`- Fuente verificada: ${p.sourceCheckedAt||'N/D'}`);if(p.category==='FCI')l.push(`- Rendimientos mensuales: ${JSON.stringify(p.monthlyReturns||{})}`,`- YTD publicado: ${p.publishedYtdReturn??'N/D'}`);});
 l.push('','## Historial',`Registros de verificación: ${snapshots.length}`,'','## Pedido','Analiza este portfolio usando únicamente estos datos. Resume riesgos y oportunidades, detecta información faltante o desactualizada y prioriza qué debería verificar primero.');
 return l.join('\n');
};
export const downloadPortfolioMarkdown=(positions,snapshots)=>download(new Blob([buildPortfolioLlmMarkdown(positions,snapshots)],{type:'text/markdown;charset=utf-8'}),`portfolio-llm-${new Date().toISOString().slice(0,10)}.md`);
